#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# HTTP response to contain a custom header (on web-01 and web-02)
var=$(hostname)
new_string="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
new_string2="server {\n\tadd_header X-Served-By $var;"
