#!/usr/bin/env bash
#displays numbers from 1 to 20
#4 bad luck from china, 9  bad luck from china, 17 bad luck from italy

i=0

while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	((i++))
done
